from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home, name='home'),
    path('register_patient/', register_patient, name='register_patient'),
    path('register_doctor/', register_doctor, name='register_doctor'),
    path('video/<str:room_name>/', video, name='video'),
    path('select-user/', select_patient_view, name='select-user'),
    path('patients/<int:user_id>/<int:appointment_id>/', patient_detail, name='patient_detail'),
    path('login/', login_view, name='login'),
    path('doctor_review/<int:user_id>/', doctor_review, name='doctor_review'),
    path('doctor_detail/<int:doctor_id>/', doctor_detail, name='doctor_detail'),
    path('service/<int:doctor_id>/<int:service_id>/', service_detail, name='service_detail'),
    path('calendar/<int:user_id>/', calendar, name='calendar'),
    path('appointments-history/<int:user_id>/', appointments_history, name='appointments-history'),
    path('address/', address, name='address'),
    path('dashboard/', dashboard, name='dashboard'),
    path('leave_review/<int:appointment_id>/', leave_review, name='leave_review'),
    path('create_medical_record/', create_medical_record, name='create_medical_record'),
    path('cancel_appointment/<int:appointment_id>/', cancel_appointment, name='cancel_appointment'),
    path('cancel_appointment_doctor/<int:appointment_id>/', cancel_appointment_doctor,
         name='cancel_appointment_doctor'),
    path('doctor/<int:doctor_id>/', doctor_detail, name='doctor_detail'),
    path('update_user/', update_user, name='update_user'),
    path('search_doctor/', search_doctor, name='search_doctor'),
    path('doctor_dashboard/', doctor_dashboard, name='doctor_dashboard'),
    path('print_record/<int:record_id>/', print_medical_record, name='print_medical_record'),
    path('search-and-filter/', search_and_filter, name='search_and_filter'),
    path('admin_panel', admin_panel, name='admin_panel'),
    path('admin_appointments/', admin_appointments, name='admin_appointments'),
    path('admin_users/', admin_users, name='admin_users'),
    path('admin_reviews/', admin_reviews, name='admin_reviews'),
    path('admin_doctors/', admin_doctors, name='admin_doctors'),
    path('admin_services/', admin_services, name='admin_services'),
    path('admin_cards/', admin_cards, name='admin_cards'),
    path('users/create/', create_user, name='create_user'),
    path('users/<int:user_id>/edit/', edit_user, name='edit_user'),
    path('users/<int:user_id>/delete/', delete_user, name='delete_user'),
    path('services/create/', create_service, name='create_service'),
    path('services/<int:service_id>/edit/', edit_service, name='edit_service'),
    path('services/<int:service_id>/delete/', delete_service, name='delete_service'),
    path('doctors/create/', create_doctor, name='create_doctor'),
    path('doctors/<int:doctor_id>/edit/', edit_doctor, name='edit_doctor'),
    path('doctors/<int:doctor_id>/delete/', delete_doctor, name='delete_doctor'),
    path('reviews/create/', create_review, name='create_review'),
    path('reviews/<int:review_id>/edit/', edit_review, name='edit_review'),
    path('reviews/<int:review_id>/delete/', delete_review, name='delete_review'),
    path('cards/create/', create_medicalrecord, name='create_medicalrecord'),
    path('cards/<int:record_id>/edit/', edit_medicalrecord, name='edit_medicalrecord'),
    path('cards/<int:record_id>/delete/', delete_medicalrecord, name='delete_medicalrecord'),
    path('appointments/create/', create_appointment, name='create_appointment'),
    path('appointments/<int:appointment_id>/edit/', edit_appointment, name='edit_appointment'),
    path('appointments/<int:appointment_id>/delete/', delete_appointment, name='delete_appointment'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
