# Generated by Django 5.1.3 on 2025-04-23 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.appointment",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="description",
            field=models.TextField(
                default="Нет описания", verbose_name="Описание приёма"
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="prescription",
            field=models.TextField(
                blank=True, verbose_name="Назначения и рекомендации"
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="results",
            field=models.TextField(verbose_name="Результаты обследования"),
        ),
    ]
