# Generated by Django 5.1.3 on 2025-04-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_medicalrecord_appointment_medicalrecord_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="appointment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.appointment",
            ),
        ),
    ]
